

public enum ErrorCode {
    STUDENT_NOT_FOUND,
    TEACHER_NOT_FOUND,
    INSUFFICIENT_FUNDS,
    INVALID_INPUT,
    DUPLICATE_ENTRY,
    OPERATION_NOT_ALLOWED,
    DATA_VALIDATION_ERROR,
    PAYMENT_PROCESSING_ERROR
}
